spring.application.name=serviceCounter

spring.flyway.enabled=false

server.port=8081

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never